name: Deploy to AWS

# Manual workflow
on: workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
  
      - name: setup-terraform
        uses: hashicorp/setup-terraform@v1

      - name: get-credentials
        run: ${{secrets.AWS_CREDENTIALS}} > ~/.aws/credentials

      - name: terraform-init
        run: terraform -chdir=./mysql init

      - name: terraform-plan
        run: terraform -chdir=./mysql destroy