name: Destroy rds database

# Manual workflow
on: workflow_dispatch

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
  AWS_DEFAULT_REGION: 'us-east-1'
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

jobs:
  terraform:
    runs-on: ubuntu-latest


    steps:
      - name: checkout
        uses: actions/checkout@v2
  
      - name: setup-terraform
        uses: hashicorp/setup-terraform@v1

      - name: terraform-init
        run: terraform -chdir=./mysql init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=mysql.tfstate" -backend-config="region=us-east-1"

      # There's AWS bug on Lambda's ENI, we have to wait for a few minutes after the Lambda has been destroyed for the ENI to be released.
      # The destroy action will fail if the ENI is not released yet.
      # You can check the ENI on VPC > Network Interfaces, look for those marked with "lambda-rds-sg" security group.
      - name: terraform-destroy
        run: terraform -chdir=./mysql destroy -auto-approve -var "MYSQL_USERNAME=" -var "MYSQL_PASSWORD="